import type { Category, Product, Project } from "./types";

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "panels",
    name: "الألواح الشمسية",
    description: "ألواح شمسية عالية الكفاءة بتقنيات HJT و TOPCON، مع كفاءة تصل إلى 23.21% وضمان أداء يصل إلى 30 عاماً.",
    icon: "Sun",
    image: "",
    order: 1,
  },
  {
    id: "inverters",
    name: "الانفرترات",
    description: "انفرترات طاقة عالية الكفاءة بأنظمة هجينة On-Grid / Off-Grid، بكفاءة تحويل تصل إلى 98% ومراقبة عن بعد.",
    icon: "Zap",
    image: "",
    order: 2,
  },
  {
    id: "batteries",
    name: "البطاريات",
    description: "حلول تخزين طاقة متطورة ببطاريات ليثيوم أيون عالية السعة، مع أنظمة إدارة ذكية وعمر افتراضي يصل إلى 10 سنوات.",
    icon: "BatteryCharging",
    image: "",
    order: 3,
  },
  {
    id: "cables",
    name: "الكابلات",
    description: "كابلات AC وكابلات طاقة شمسية متينة مصممة للظروف البيئية القاسية، مقاومة للأشعة فوق البنفسجية مع عزل مزدوج.",
    icon: "Cable",
    image: "",
    order: 4,
  },
];

export const DEFAULT_PRODUCTS: Product[] = [
  {
    id: "ae-solar-panels",
    categoryId: "panels",
    name: "ألواح AE Solar",
    brand: "AE Solar",
    description: "الموزع المعتمد في اليمن لشركة إي سولار العالمية، ألواح شمسية عالية الكفاءة بتقنيات متطورة وضمان يصل إلى 30 عاماً.",
    features: [
      "تقنيات HJT و TOPCON المتطورة",
      "كفاءة تصل إلى 23.21%",
      "ضمان أداء 30 عاماً",
      "تصميم مقاوم للظروف القاسية",
    ],
    image: "/products/panel.png",
    accent: "from-emerald-500 to-brand-blue",
    order: 1,
  },
  {
    id: "aesolar-meteor",
    categoryId: "panels",
    name: "AE Solar METEOR",
    brand: "AE Solar",
    description: "ألواح طاقة شمسية بتقنية n-Type TOPCon المتقدمة، مصممة لتوفير أقصى درجات الكفاءة بقدرات تتراوح بين 415W إلى 725W.",
    features: [
      "خيارات خلايا متعددة: 182mm و 210mm و G12R المستطيلة",
      "متاح بتصاميم أحادية الوجه، ثنائية الوجه بزجاج مزدوج، وأسود بالكامل",
      "ضمان أداء يصل إلى 30 عاماً وضمان منتج حتى 30 عاماً"
    ],
    image: "/products/aesolar-meteor.jpg",
    accent: "from-emerald-500 to-brand-green-dark",
    order: 1,
  },
  {
    id: "aesolar-horizon",
    categoryId: "panels",
    name: "AE Solar HORIZON",
    brand: "AE Solar",
    description: "ألواح شمسية مخصصة لمظلات السيارات (Carports) بتقنية n-Type TOPCon، بقدرات تتراوح بين 415W و 435W.",
    features: [
      "مصمم خصيصاً هندسياً لتركيبات مظلات السيارات الشمسية",
      "هيكل زجاجي مزدوج ثنائي الوجه مع نفاذية معززة للضوء",
      "يعتمد على تكوين خلايا TOPCon بحجم 182mm"
    ],
    image: "/products/aesolar-horizon.jpg",
    accent: "from-blue-500 to-indigo-600",
    order: 2,
  },
  {
    id: "aesolar-aurora",
    categoryId: "panels",
    name: "AE Solar AURORA",
    brand: "AE Solar",
    description: "سلسلة ألواح تعتمد على تقنية Mono-crystalline PERC الموثوقة، بقدرات مرنة تتراوح بين 360W إلى 660W لتناسب مختلف المشاريع.",
    features: [
      "طيف واسع من الخلايا يشمل أحجام 166mm و 182mm و 210mm",
      "تكوينات أحادية الوجه، ثنائية بزجاج أحادي، وثنائية بزجاج مزدوج",
      "يتضمن خيارات بصرية باللون الأسود بالكامل (Full-black)"
    ],
    image: "/products/aesolar-aurora.jpg",
    accent: "from-cyan-500 to-brand-blue",
    order: 3,
  },
  {
    id: "aesolar-comet",
    categoryId: "panels",
    name: "AE Solar COMET",
    brand: "AE Solar",
    description: "ألواح شمسية فائقة الإنتاجية بتقنية (HJT) المتطورة، مصممة للمشاريع الكبرى بقدرات تتراوح بين 700W إلى 720W.",
    features: [
      "تقنية خلايا HJT عالية الكفاءة (Half-cut)",
      "وحدة زجاجية مزدوجة ثنائية الوجه مصممة لإنتاج طاقة فائق",
      "مبنية على خلايا كبيرة الحجم 210mm"
    ],
    image: "/products/aesolar-comet.jpg",
    accent: "from-teal-500 to-emerald-600",
    order: 4,
  },
  {
    id: "aesolar-alpine",
    categoryId: "panels",
    name: "AE Solar ALPINE",
    brand: "AE Solar",
    description: "ألواح شمسية شديدة التحمل بتقنية n-Type TOPCon، مصممة لمقاومة الظروف الجوية القاسية بقدرات من 420W إلى 595W.",
    features: [
      "هيكل شديد التحمل هندسياً لمقاومة الطقس المتطرف",
      "معتمد لتحمل ضربات البرد بحجم 40mm (تصنيف HW4)",
      "زجاج أمان مقسى بسمك 3.2mm وإطار من سبائك الألومنيوم T6 عالي القوة"
    ],
    image: "/products/aesolar-alpine.jpg",
    accent: "from-slate-600 to-slate-800",
    order: 5,
  },
  {
    id: "sinexcel-inverters",
    categoryId: "inverters",
    name: "انفرترات Sinexcel",
    brand: "Sinexcel",
    description: "انفرترات طاقة عالية الكفاءة من شركة سنكسل العالمية، بمجموعة متنوعة من السعات والمواصفات.",
    features: [
      "أنظمة هجينة ومتوافقة مع البطاريات",
      "كفاءة تحويل تصل إلى 98%",
      "مراقبة عن بعد وتحكم ذكي",
      "نطاق سعات من 3 إلى 50 كيلوواط",
    ],
    image: "/products/inverter.jpg",
    accent: "from-brand-blue to-indigo-600",
    order: 2,
  },
  {
    id: "sinexcel-3ph-hv",
    categoryId: "inverters",
    name: "Sinexcel iSUNA — Hybrid Three Phase HV (10-20kW)",
    brand: "Sinexcel",
    description: "انفرتر هجين ثلاثي الأطوار بجهد عالي، يدعم سعات من 10 إلى 20 كيلوواط، مع تقنية SiC وكفاءة قصوى تصل إلى 98.20%، ومنفذي بطارية مستقلين، وقدرة على توازن 100% للأطوار الثلاثة.",
    features: [
      "يدعم 100% توازن للأطوار الثلاثة",
      "تحميل زائد فوري 130-200% (60 ثانية)",
      "إمكانية توصيل 15 وحدة بالتوازي",
      "منفذي بطارية مستقلين (خليط بطاريات قديمة وجديدة)",
      "نسبة DC/AC تصل إلى 1.5 مرة",
    ],
    image: "/products/sinexcel-3ph-hv.jpg",
    accent: "from-brand-blue to-indigo-600",
    order: 3,
  },
  {
    id: "sinexcel-onoff-3ph-hv",
    categoryId: "inverters",
    name: "Sinexcel iSUNA — On/Off-Grid Three Phase HV (22-50kW)",
    brand: "Sinexcel",
    description: "انفرتر هجين ثلاثي الأطوار بجهد عالي يعمل على/خارج الشبكة، يدعم سعات من 22 إلى 50 كيلوواط، بتقنية SiC وكفاءة قصوى 98.6%، مع 4 MPPTs ومنفذ مولد احترافي بتيار 150 أمبير.",
    features: [
      "تقنية SiC بكفاءة قصوى 98.6%",
      "4 MPPTs بتيار دخول 40A لتوافق أعلى",
      "منفذي بطارية مستقلين لخليط البطاريات",
      "تحميل زائد 150% مع خيار دالة AFCI",
      "6 وحدات بالتوازي (وضع خارج الشبكة)",
      "منفذ مولد احترافي بتيار 150A",
    ],
    image: "/products/sinexcel-onoff-3ph-hv.jpg",
    accent: "from-indigo-600 to-brand-blue",
    order: 4,
  },
  {
    id: "sinexcel-offgrid-1ph-lv",
    categoryId: "inverters",
    name: "Sinexcel iSUNA — Off-Grid Single Phase LV (3-12kW)",
    brand: "Sinexcel",
    description: "انفرتر هجين خارج الشبكة أحادي الطور بجهد منخفض، يدعم سعات من 3 إلى 12 كيلوواط، مع مروحة ذكية فائقة الصمت، وكفاءة قصوى 97.5%، وضمان 5 سنوات.",
    features: [
      "دعم 6 وحدات بالتوازي (3-6kW فقط)",
      "دخل طاقة شمسية 125-250% مع 2-4 MPPTs",
      "دخل شبكة 190-460% (تيار 60A-100A)",
      "تغذية الأحمال وشحن البطارية بالتوازي",
      "مروحة ذكية فائقة الصمت",
      "ضمان قياسي 5 سنوات",
    ],
    image: "/products/sinexcel-offgrid-1ph-lv.jpg",
    accent: "from-brand-blue to-cyan-600",
    order: 5,
  },
  {
    id: "sinexcel-osol-sou-g2",
    categoryId: "inverters",
    name: "Sinexcel iSUNA — O-SOL & SOU-G2 Series (1.5-6kW)",
    brand: "Sinexcel",
    description: "انفرتر هجين خارج الشبكة أحادي الطور بجهد منخفض، سلسلة O-SOL و SOU-G2، يدعم سعات من 1.5 إلى 6 كيلوواط، بحجم مصغر وتبريد ذكي فائق الصمت ودعم OTA وتطبيق للمراقبة.",
    features: [
      "دخل مولد >200% ودخل شبكة >200%",
      "قدرة تحميل زائد 130-260%",
      "دعم حتى 6 وحدات بالتوازي",
      "حجم مصغر وتبريد ذكي فائق الصمت",
      "دعم تحديث OTA ومراقبة عبر التطبيق",
    ],
    image: "/products/sinexcel-osol-sou-g2.jpg",
    accent: "from-cyan-600 to-brand-blue",
    order: 6,
  },
  {
    id: "sunwoda-batteries",
    categoryId: "batteries",
    name: "بطاريات Sunwoda",
    brand: "Sunwoda",
    description: "حلول تخزين طاقة متطورة من شركة سنودا العالمية، بقدرات متنوعة وتصميمات مرنة.",
    features: [
      "بطاريات ليثيوم أيون عالية السعة",
      "تصميم قابل للتوسعة والتركيب",
      "عمر افتراضي طويل يصل إلى 10 سنوات",
      "أنظمة إدارة ذكية للبطارية (BMS)",
    ],
    image: "/products/battery.svg",
    accent: "from-emerald-400 to-teal-600",
    order: 3,
  },
];

export const DEFAULT_PROJECTS: Project[] = [
  {
    id: "hubail-water",
    title: "مشروع مياه حبيل الريدة",
    type: "نظام هجين PV-Diesel",
    capacity: "409.2",
    unit: "كيلوواط",
    location: "اليمن",
    description: "نظام طاقة شمسية PV-Diesel (هجين) بقدرة 409.2 كيلوواط باستخدام ألواح AE Solar، لتشغيل نظام ضخ مياه مستدام يخدم المجتمع المحلي بأكمله.",
    image: "/projects/water.jpg",
    accent: "from-emerald-500 via-brand-green to-brand-blue",
    date: "2024",
    order: 1,
  },
  {
    id: "commercial-dabash-store",
    title: "نظام طاقة هجين متكامل لمحل دباش",
    type: "مشروع تجاري",
    capacity: "12", // Estimated logical capacity based on the 3 lithium modules and inverter size
    unit: "kW",
    location: "صنعاء، اليمن",
    description: "تصميم وتركيب نظام طاقة شمسية هجين (Hybrid) لتأمين تغذية كهربائية مستقرة ومستمرة لمحل دباش التجاري. شمل المشروع تركيب انفرتر ذكي عالي الكفاءة، وربطه ببنك تخزين مكون من ثلاث وحدات بطاريات ليثيوم متطورة لضمان تشغيل الأحمال الحساسة على مدار الساعة. تم تنفيذ اللوحات الكهربائية والتمديدات (AC/DC) وفق أعلى معايير السلامة والتنظيم لضمان الكفاءة القصوى والعمر الافتراضي الطويل.",
    date: "2026",
    image: "/projects/dabash-store.jpg",
    accent: "from-brand-blue to-emerald-500", // A clean blue-to-green gradient that matches the tech vibe
    order: 5,
  },
  {
    id: "agri-water-pump-120kw",
    title: "محطة ضخ مياه زراعية متكاملة",
    type: "مشروع زراعي",
    capacity: "120",
    unit: "kW",
    location: "مزارع تهامة، الحديدة",
    description: "تصميم وتوريد وتركيب منظومة طاقة شمسية متكاملة لتشغيل مضخات مياه غاطسة بقدرات عالية. تهدف المنظومة إلى ري مساحات زراعية شاسعة وتقليل الاعتماد على الديزل بنسبة 100%. تم استخدام أحدث انفرترات الضخ المتخصصة من Sinexcel وألواح AE Solar عالية الكفاءة لضمان أطول فترة ضخ يومية واستقرار مستدام للقطاع الزراعي.",
    date: "2024",
    image: "/projects/agriculture.jpg", 
    accent: "from-cyan-500 to-blue-600",
    order: 4,
  },
  {
    id: "sanaa-commercial",
    title: "محطة تجارية – صنعاء",
    type: "نظام هجين PV-Diesel",
    capacity: "316.8",
    unit: "كيلوواط",
    location: "صنعاء",
    description: "تركيب نظام طاقة شمسية PV-Diesel (هجين) متكامل بقدرة 316.8 كيلوواط لمحطة تجارية كبرى في العاصمة صنعاء.",
    image: "/projects/commercial.jpg",
    accent: "from-brand-blue to-emerald-500",
    date: "2024",
    order: 2,
  },
  {
    id: "mall-project",
    title: "مركز تجاري (مول)",
    type: "نظام هجين مع تخزين",
    capacity: "28.4",
    unit: "كيلوواط",
    location: "اليمن",
    description: "نظام شمسي هجين بقدرة 28.4 كيلوواط مع بطاريات ليثيوم لتشغيل مركز تجاري كبير، مع تخزين طاقة للاستخدام الليلي.",
    image: "/projects/mall.jpg",
    accent: "from-teal-500 to-brand-blue",
    date: "2023",
    order: 3,
  },
];
